In [1]:
import pandas as pd

# Import data dari file cycles.csv
data_cycles = pd.read_csv("/workspaces/Ds_jala/Data/cycles.csv")

# Import data dari file farms.csv
data_farms = pd.read_csv("/workspaces/Ds_jala/Data/farms.csv")

# Import data dari file fasting.csv
data_fasting = pd.read_csv("/workspaces/Ds_jala/Data/fasting.csv")

# Import data dari file fastings.csv
data_fastings = pd.read_csv("/workspaces/Ds_jala/Data/fastings.csv")

# Import data dari file feed_tray.csv
data_feed_tray = pd.read_csv("/workspaces/Ds_jala/Data/feed_tray.csv")

# Import data dari file feeds.csv
data_feeds = pd.read_csv("/workspaces/Ds_jala/Data/feeds.csv")

# Import data dari file harvests.csv
data_harvests = pd.read_csv("/workspaces/Ds_jala/Data/harvests.csv")

# Import data dari file measurements.csv
data_measurements = pd.read_csv(r"/workspaces/Ds_jala/Data/measurements.csv")

# Import data dari file mortalities.csv
data_mortalities = pd.read_csv("/workspaces/Ds_jala/Data/mortalities.csv")

# Import data dari file ponds.csv
data_ponds = pd.read_csv("/workspaces/Ds_jala/Data/ponds.csv")

# Import data dari file samplings.csv
data_samplings = pd.read_csv("/workspaces/Ds_jala/Data/samplings.csv")

In [2]:
# Now drop duplicates (consider inplace=True for efficiency)
for df, name in zip(
    [
        data_cycles,
        data_farms,
        data_fasting,
        data_fastings,
        data_feed_tray,
        data_feeds,
        data_harvests,
        data_measurements,
        data_mortalities,
        data_ponds,
        data_samplings,
    ],
    [
        "data_cycles",
        "data_farms",
        "data_fasting",
        "data_fastings",
        "data_feed_tray",
        "data_feeds",
        "data_harvests",
        "data_measurements",
        "data_mortalities",
        "data_ponds",
        "data_samplings",
    ],
):
    df.drop_duplicates(inplace=True)  # Drop duplicates and modify DataFrame in-place

# Print number of duplicates after dropping
print("\nAnalisis Duplikat (setelah dihapus):")
for df, name in zip(
    [
        data_cycles,
        data_farms,
        data_fasting,
        data_fastings,
        data_feed_tray,
        data_feeds,
        data_harvests,
        data_measurements,
        data_mortalities,
        data_ponds,
        data_samplings,
    ],
    [
        "data_cycles",
        "data_farms",
        "data_fasting",
        "data_fastings",
        "data_feed_tray",
        "data_feeds",
        "data_harvests",
        "data_measurements",
        "data_mortalities",
        "data_ponds",
        "data_samplings",
    ],
):
    print(f"- {name}: {df.duplicated().sum()}")  # Print number of duplicates remaining

Analisis Duplikat (setelah dihapus):
- data_cycles: 0
- data_farms: 0
- data_fasting: 0
- data_fastings: 0
- data_feed_tray: 0
- data_feeds: 0
- data_harvests: 0
- data_measurements: 0
- data_mortalities: 0
- data_ponds: 0
- data_samplings: 0

In [3]:
import pandas as pd

# Analyze null values
print("\nAnalisis Nilai Null (sebelum dihapus):")
for df, name in zip(
    [
        data_cycles,
        data_farms,
        data_fasting,
        data_fastings,
        data_feed_tray,
        data_feeds,
        data_harvests,
        data_measurements,
        data_mortalities,
        data_ponds,
        data_samplings,
    ],
    [
        "data_cycles",
        "data_farms",
        "data_fasting",
        "data_fastings",
        "data_feed_tray",
        "data_feeds",
        "data_harvests",
        "data_measurements",
        "data_mortalities",
        "data_ponds",
        "data_samplings",
    ],
):
    print(f"- {name}: {df.isnull().sum()}")  # Print number of null values before dropping

# Drop rows with null values (consider subset of columns if needed)
for df, name in zip(
    [
        data_cycles,
        data_farms,
        data_fasting,
        data_fastings,
        data_feed_tray,
        data_feeds,
        data_harvests,
        data_measurements,
        data_mortalities,
        data_ponds,
        data_samplings,
    ],
    [
        "data_cycles",
        "data_farms",
        "data_fasting",
        "data_fastings",
        "data_feed_tray",
        "data_feeds",
        "data_harvests",
        "data_measurements",
        "data_mortalities",
        "data_ponds",
        "data_samplings",
    ],
):
    df.dropna(inplace=True)  # Drop rows with any null value

# Print number of null values after dropping (optional)
print("\nAnalisis Nilai Null (setelah dihapus):")
for df, name in zip(
    [
        data_cycles,
        data_farms,
        data_fasting,
        data_fastings,
        data_feed_tray,
        data_feeds,
        data_harvests,
        data_measurements,
        data_mortalities,
        data_ponds,
        data_samplings,
    ],
    [
        "data_cycles",
        "data_farms",
        "data_fasting",
        "data_fastings",
        "data_feed_tray",
        "data_feeds",
        "data_harvests",
        "data_measurements",
        "data_mortalities",
        "data_ponds",
        "data_samplings",
    ],
):
    print(f"- {name}: {df.isnull().sum()}")  # Print number of null values remaining

Analisis Nilai Null (sebelum dihapus):
- data_cycles: id                           0
pond_id                      0
species_id                 798
total_seed                   0
started_at                   0
finished_at                  1
remark                    1231
created_at                   0
updated_at                   0
area                         0
initial_age                 47
limit_weight_per_area        7
target_cultivation_day       3
target_size                  4
extracted_at                 0
subscription_type            0
ordered_at                1474
hatchery_id                458
total_seed_type            242
hatchery_name              458
pond_name                    0
pond_length                  6
pond_width                   6
pond_depth                 118
dtype: int64
- data_farms: id           0
province    72
regency     93
timezone     0
dtype: int64
- data_fasting: logged_date     0
cycle_id        0
fasting        17
dtype: int64
- data_fastings: logged_date     0
cycle_id        0
fasting        38
dtype: int64
- data_feed_tray: id                             0
logged_at                      0
feed_logged_at                 0
cycle_id                       0
tray_number                    0
feed_remaining_percent         0
remark                    140283
created_at                     0
updated_at                     0
local_feed_logged_at           0
dtype: int64
- data_feeds: cycle_id      0
logged_at    17
quantity     17
dtype: int64
- data_harvests: cycle_id            0
updated_at          0
size                0
created_at          0
weight              0
id                  0
harvested_at        0
status            263
selling_price    1793
dtype: int64
- data_measurements: pond_id                     0
cycle_id                    0
measured_date               0
morning_temperature     41855
evening_temperature     49839
morning_do              61324
evening_do              65098
morning_salinity        46388
evening_salinity        73957
morning_pH              20115
evening_pH              78101
transparency            61750
turbidity              138884
ammonia                135302
nitrate                136888
nitrite                129293
alkalinity             125533
hardness               133525
calcium                132458
magnesium              132430
carbonate              133762
bicarbonate            132372
tom                    131774
total_plankton_        126429
dtype: int64
- data_mortalities: id                0
cycle_id          0
quantity          0
recorded_at       0
created_at        0
updated_at        0
average_weight    0
dtype: int64
- data_ponds: id                    0
farm_id               0
length               23
width                29
deep                 92
created_at            0
updated_at            0
record_id             0
extracted_at          0
max_seed_density    203
dtype: int64
- data_samplings: cycle_id              0
updated_at            0
sampled_at            0
created_at            0
average_weight        0
id                    0
remark            13693
dtype: int64

Analisis Nilai Null (setelah dihapus):
- data_cycles: id                        0
pond_id                   0
species_id                0
total_seed                0
started_at                0
finished_at               0
remark                    0
created_at                0
updated_at                0
area                      0
initial_age               0
limit_weight_per_area     0
target_cultivation_day    0
target_size               0
extracted_at              0
subscription_type         0
ordered_at                0
hatchery_id               0
total_seed_type           0
hatchery_name             0
pond_name                 0
pond_length               0
pond_width                0
pond_depth                0
dtype: int64
- data_farms: id          0
province    0
regency     0
timezone    0
dtype: int64
- data_fasting: logged_date    0
cycle_id       0
fasting        0
dtype: int64
- data_fastings: logged_date    0
cycle_id       0
fasting        0
dtype: int64
- data_feed_tray: id                        0
logged_at                 0
feed_logged_at            0
cycle_id                  0
tray_number               0
feed_remaining_percent    0
remark                    0
created_at                0
updated_at                0
local_feed_logged_at      0
dtype: int64
- data_feeds: cycle_id     0
logged_at    0
quantity     0
dtype: int64
- data_harvests: cycle_id         0
updated_at       0
size             0
created_at       0
weight           0
id               0
harvested_at     0
status           0
selling_price    0
dtype: int64
- data_measurements: pond_id                0.0
cycle_id               0.0
measured_date          0.0
morning_temperature    0.0
evening_temperature    0.0
morning_do             0.0
evening_do             0.0
morning_salinity       0.0
evening_salinity       0.0
morning_pH             0.0
evening_pH             0.0
transparency           0.0
turbidity              0.0
ammonia                0.0
nitrate                0.0
nitrite                0.0
alkalinity             0.0
hardness               0.0
calcium                0.0
magnesium              0.0
carbonate              0.0
bicarbonate            0.0
tom                    0.0
total_plankton_        0.0
dtype: float64
- data_mortalities: id                0
cycle_id          0
quantity          0
recorded_at       0
created_at        0
updated_at        0
average_weight    0
dtype: int64
- data_ponds: id                  0
farm_id             0
length              0
width               0
deep                0
created_at          0
updated_at          0
record_id           0
extracted_at        0
max_seed_density    0
dtype: int64
- data_samplings: cycle_id          0
updated_at        0
sampled_at        0
created_at        0
average_weight    0
id                0
remark            0
dtype: int64

In [22]:
data_cycles.corr()

/tmp/ipykernel_34924/1958858392.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_cycles.corr()

,id,pond_id,species_id,total_seed,area,initial_age,limit_weight_per_area,target_cultivation_day,target_size,hatchery_id,pond_length,pond_width,pond_depth
id,1.000000,0.501823,NaN,-0.098854,-0.056389,-0.145972,-0.072224,0.272441,-0.161704,0.199871,-0.032734,-0.118662,-0.121224
pond_id,0.501823,1.000000,NaN,0.043258,0.023562,0.048430,-0.019908,0.178035,-0.015701,-0.106901,0.058794,0.053161,-0.042736
species_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_seed,-0.098854,0.043258,NaN,1.000000,0.251740,0.273364,-0.029633,0.110196,-0.199631,0.077559,0.148603,0.659491,-0.071679
area,-0.056389,0.023562,NaN,0.251740,1.000000,0.072571,-0.006615,-0.036657,0.014242,0.138200,0.242672,0.265464,-0.032451
initial_age,-0.145972,0.048430,NaN,0.273364,0.072571,1.000000,0.117373,-0.240266,0.178059,0.122919,0.262182,0.274406,0.092827
limit_weight_per_area,-0.072224,-0.019908,NaN,-0.029633,-0.006615,0.117373,1.000000,-0.053902,0.157729,-0.037897,0.012336,0.079686,-0.008040
target_cultivation_day,0.272441,0.178035,NaN,0.110196,-0.036657,-0.240266,-0.053902,1.000000,-0.267139,0.076497,-0.083404,0.036556,-0.226397
target_size,-0.161704,-0.015701,NaN,-0.199631,0.014242,0.178059,0.157729,-0.267139,1.000000,-0.164960,0.178641,-0.055613,0.117244
hatchery_id,0.199871,-0.106901,NaN,0.077559,0.138200,0.122919,-0.037897,0.076497,-0.164960,1.000000,0.086496,0.126759,-0.029923
pond_length,-0.032734,0.058794,NaN,0.148603,0.242672,0.262182,0.012336,-0.083404,0.178641,0.086496,1.000000,0.181612,-0.081221
pond_width,-0.118662,0.053161,NaN,0.659491,0.265464,0.274406,0.079686,0.036556,-0.055613,0.126759,0.181612,1.000000,-0.071188
pond_depth,-0.121224,-0.042736,NaN,-0.071679,-0.032451,0.092827,-0.008040,-0.226397,0.117244,-0.029923,-0.081221,-0.071188,1.000000

In [23]:
data_harvests.corr()

/tmp/ipykernel_34924/284887663.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data_harvests.corr()

               cycle_id      size    weight        id  selling_price
cycle_id       1.000000  0.018279  0.015044  0.986595       0.019056
size           0.018279  1.000000 -0.016113 -0.000797      -0.031204
weight         0.015044 -0.016113  1.000000  0.017506       0.670056
id             0.986595 -0.000797  0.017506  1.000000       0.020926
selling_price  0.019056 -0.031204  0.670056  0.020926       1.000000